backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
local_backend: true
media_folder: public/images
public_folder: images
collections:
  - name: "homeAbout"
    label: "About"
    files:
      - name: "content-heroAbout"
        label: "Hero and About"
        file: "content/homeData/content-heroAbout.md"
        fields:
          - {
              label: "Hero Image",
              name: "heroImage",
              widget: "image",
              choose_url: true,
              allow_multiple: false,
            }

          - { label: "About Text", name: "aboutTitle", widget: "string" }

          - { label: "About Body", name: "aboutText", widget: "string" }

      - name: "content-productTypes"
        label: "Product Types"
        file: "content/homeData/content-productTypes.md"
        fields:
          - label: "Product List"
            name: "productTypes"
            widget: list
            edit: false
            fields:
              - { label: "Product Name", name: "name", widget: "string" }
              - {
                  label: "Product Description",
                  name: "description",
                  widget: "text",
                }
              - {
                  label: "Product Image",
                  name: "image",
                  widget: "image",
                  choose_url: true,
                  allow_multiple: false,
                }
